export * from './appointment.reducer';
export * from './appointmentsForDoctor.reducer';
export * from './appointmentsForPatient.reducer';
export * from './login.reducer';
export * from './notification.reducer';
export * from './profile.reducer';
export * from './registration.reducer';
export * from './resolution.reducer';
export * from './resolutions.reducer';
